2015-03-05 18:46:05,913 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
grails.validation.ValidationException: Validation Error(s) occurred during save():
- Field error in object 'ejemplopostgress.Alumnos' on field 'fechaNac': rejected value [09/09/2001]; codes [ejemplopostgress.Alumnos.fechaNac.typeMismatch.error,ejemplopostgress.Alumnos.fechaNac.typeMismatch,alumnos.fechaNac.typeMismatch.error,alumnos.fechaNac.typeMismatch,typeMismatch.ejemplopostgress.Alumnos.fechaNac,typeMismatch.fechaNac,typeMismatch.java.util.Date,typeMismatch]; arguments [fechaNac]; default message [Unparseable date: "09/09/2001"]

	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractSavePersistentMethod.doInvokeInternal(AbstractSavePersistentMethod.java:190)
	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractDynamicPersistentMethod.invoke(AbstractDynamicPersistentMethod.java:68)
	at org.codehaus.groovy.grails.orm.hibernate.HibernateGormInstanceApi.save(HibernateGormInstanceApi.groovy:195)
	at ejemplopostgress.Alumnos.save(Alumnos.groovy)
	at ejemplopostgress.Alumnos$save$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at BootStrap$_closure1.doCall(BootStrap.groovy:7)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1081)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:417)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
	at grails.util.Environment.executeForEnvironment(Environment.java:320)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
	at org.codehaus.groovy.grails.commons.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:60)
	at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:78)
	at org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener.initWebApplicationContext(GrailsContextLoaderListener.java:110)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4992)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5490)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2015-03-05 18:46:05,915 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
grails.validation.ValidationException: Validation Error(s) occurred during save():
- Field error in object 'ejemplopostgress.Alumnos' on field 'fechaNac': rejected value [09/09/2001]; codes [ejemplopostgress.Alumnos.fechaNac.typeMismatch.error,ejemplopostgress.Alumnos.fechaNac.typeMismatch,alumnos.fechaNac.typeMismatch.error,alumnos.fechaNac.typeMismatch,typeMismatch.ejemplopostgress.Alumnos.fechaNac,typeMismatch.fechaNac,typeMismatch.java.util.Date,typeMismatch]; arguments [fechaNac]; default message [Unparseable date: "09/09/2001"]

	at BootStrap$_closure1.doCall(BootStrap.groovy:7)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
	at grails.util.Environment.executeForEnvironment(Environment.java:320)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2015-03-05 18:46:05,915 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
grails.validation.ValidationException: Validation Error(s) occurred during save():
- Field error in object 'ejemplopostgress.Alumnos' on field 'fechaNac': rejected value [09/09/2001]; codes [ejemplopostgress.Alumnos.fechaNac.typeMismatch.error,ejemplopostgress.Alumnos.fechaNac.typeMismatch,alumnos.fechaNac.typeMismatch.error,alumnos.fechaNac.typeMismatch,typeMismatch.ejemplopostgress.Alumnos.fechaNac,typeMismatch.fechaNac,typeMismatch.java.util.Date,typeMismatch]; arguments [fechaNac]; default message [Unparseable date: "09/09/2001"]

	at BootStrap$_closure1.doCall(BootStrap.groovy:7)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
	at grails.util.Environment.executeForEnvironment(Environment.java:320)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2015-03-05 18:46:05,915 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
grails.validation.ValidationException: Validation Error(s) occurred during save():
- Field error in object 'ejemplopostgress.Alumnos' on field 'fechaNac': rejected value [09/09/2001]; codes [ejemplopostgress.Alumnos.fechaNac.typeMismatch.error,ejemplopostgress.Alumnos.fechaNac.typeMismatch,alumnos.fechaNac.typeMismatch.error,alumnos.fechaNac.typeMismatch,typeMismatch.ejemplopostgress.Alumnos.fechaNac,typeMismatch.fechaNac,typeMismatch.java.util.Date,typeMismatch]; arguments [fechaNac]; default message [Unparseable date: "09/09/2001"]

	at BootStrap$_closure1.doCall(BootStrap.groovy:7)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
	at grails.util.Environment.executeForEnvironment(Environment.java:320)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2015-03-05 18:46:05,915 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
grails.validation.ValidationException: Validation Error(s) occurred during save():
- Field error in object 'ejemplopostgress.Alumnos' on field 'fechaNac': rejected value [09/09/2001]; codes [ejemplopostgress.Alumnos.fechaNac.typeMismatch.error,ejemplopostgress.Alumnos.fechaNac.typeMismatch,alumnos.fechaNac.typeMismatch.error,alumnos.fechaNac.typeMismatch,typeMismatch.ejemplopostgress.Alumnos.fechaNac,typeMismatch.fechaNac,typeMismatch.java.util.Date,typeMismatch]; arguments [fechaNac]; default message [Unparseable date: "09/09/2001"]

	at BootStrap$_closure1.doCall(BootStrap.groovy:7)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
	at grails.util.Environment.executeForEnvironment(Environment.java:320)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2015-03-05 18:46:05,916 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
grails.validation.ValidationException: Validation Error(s) occurred during save():
- Field error in object 'ejemplopostgress.Alumnos' on field 'fechaNac': rejected value [09/09/2001]; codes [ejemplopostgress.Alumnos.fechaNac.typeMismatch.error,ejemplopostgress.Alumnos.fechaNac.typeMismatch,alumnos.fechaNac.typeMismatch.error,alumnos.fechaNac.typeMismatch,typeMismatch.ejemplopostgress.Alumnos.fechaNac,typeMismatch.fechaNac,typeMismatch.java.util.Date,typeMismatch]; arguments [fechaNac]; default message [Unparseable date: "09/09/2001"]

	at BootStrap$_closure1.doCall(BootStrap.groovy:7)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
	at grails.util.Environment.executeForEnvironment(Environment.java:320)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
